###
GET http://localhost:3000/contacts/
###
GET http://localhost:3000/contacts/644d7bd226896f63db09012d
###
GET http://localhost:3000/contacts/6450498f2195511de19a5ab4
###
GET http://localhost:3000/contacts/645049d92195511de19a5ab5
###
DELETE http://localhost:3000/contacts/64642e8ef70dbbd47952247a HTTP/1.1
###
POST http://localhost:3000/contacts/
Content-Type: application/json

{
    "firstName": "Ashley",
    "lastName": "Weaver",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "06/19/2000"
}
###
PUT http://localhost:3000/contacts/64642dbf0fc1bd250b0adb6e HTTP/1.1
Content-Type: application/json

{
    "firstName": "Brooke",
    "lastName": "Weaver",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "06/19/2000"
}
###
PUT http://localhost:3000/contacts/64642dbf0fc1bd250b0adb6e HTTP/1.1
###
POST https://cse341-render-yq1g.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ashley",
    "lastName": "Weaver",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "06/19/2000"
}

###
PUT https://cse341-render-yq1g.onrender.com/contacts/645049d92195511de19a5ab5 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Chase",
    "lastName": "Sorenson",
    "email": "sorensonemail@test.com",
    "favoriteColor": "Maroon",
    "birthday": "12/19/2000"
}

###
DELETE https://cse341-render-yq1g.onrender.com/contacts/645049d92195511de19a5ab5 HTTP/1.1